% check_plot to review output of LyAmr_Test
M = load('input.txt');
C = load('output.txt');
A = load('averages.txt');

t = time2d(C(:,1));
cat = C(:,2);
fg = cat==1;
bg = cat==2;
tr = cat==3;
dc = cat==0;
fgpct = 100*sum(fg)/length(fg);
bgpct = 100*sum(bg)/length(fg);
trpct = 100*sum(tr)/length(fg);
dcpct = 100*sum(dc)/length(fg);
fprintf(1,'fg: %4.1f%%\nbg: %4.1f%%\ntr: %4.1f%%\ndc: %4.1f%%\n', ...
    fgpct, bgpct, trpct, dcpct);
tfg = time2d(A(:,1));
tbg = time2d(A(:,4));
V = M(:,3);
figure; plot(t, V, ...
    t(tr), V(tr), '.', ...
    t(dc), V(dc), '.', ...
    t(fg), V(fg), '.', ...
    t(bg), V(bg), '.', ...
    tfg, A(:,2), 'r*', ...
    tbg, A(:,5), 'r*'  ...
    );
legend('raw','tr','dc','fg','bg','mfg','mbg');
title('PMTA');
V = M(:,4);
figure; plot(t, V, ...
    t(tr), V(tr), '.', ...
    t(dc), V(dc), '.', ...
    t(fg), V(fg), '.', ...
    t(bg), V(bg), '.', ...
    tfg, A(:,3), 'r*', ...
    tbg, A(:,6), 'r*'  ...
    );
legend('raw','tr','dc','fg','bg','mfg','mbg');
title('UVA1');
