function phwvlct(varargin);
% phwvlct( [...] );
% Lamp C Temp
h = timeplot({'C_LMT','C_RFT','ChpCT','FAC_T'}, ...
      'Lamp C Temp', ...
      'Temp', ...
      {'C\_LMT','C\_RFT','ChpCT','FAC\_T'}, ...
      varargin{:} );
