function phwvhkpt(varargin);
% phwvhkpt( [...] );
% Power Temp
h = timeplot({'PDACS_1T','PDACS_2T','PDACS_3T','PDACS_4T','PDACS_5T'}, ...
      'Power Temp', ...
      'Temp', ...
      {'PDACS\_1T','PDACS\_2T','PDACS\_3T','PDACS\_4T','PDACS\_5T'}, ...
      varargin{:} );
