function phwvcmz(varargin);
% phwvcmz( [...] );
% Current MZ
h = timeplot({'MZ1_I','MZ2_I','MZ3_I','MZ4_I'}, ...
      'Current MZ', ...
      'MZ', ...
      {'MHZ1','MHZ2','MHZ3','MHZ4'}, ...
      varargin{:} );
