function phwvhhhhhhptp(varargin);
% phwvhhhhhhptp( [...] );
% HHHPT P
h = timeplot({'HHH1P','HHH2P','HHHDP','HPV_P'}, ...
      'HHHPT P', ...
      'P', ...
      {'HHH1P','HHH2P','HHHDP','HPV\_P'}, ...
      varargin{:} );
