function phwvlat(varargin);
% phwvlat( [...] );
% Lamp A Temp
h = timeplot({'A_LMT','ChpAT','FAA_T'}, ...
      'Lamp A Temp', ...
      'Temp', ...
      {'LMT','ChpAT','FAA\_T'}, ...
      varargin{:} );
