function phwvlaairvirv(varargin);
% phwvlaairvirv( [...] );
% A IRV IRV
h = timeplot({'A_IRV','IRVf','HtASt'}, ...
      'A IRV IRV', ...
      'IRV', ...
      {'A\_IRV','IRVf','HtASt'}, ...
      varargin{:} );
