function phwvhhhptt(varargin);
% phwvhhhptt( [...] );
% HHHPT T
h = timeplot({'HHH1T','HHH2T','HHHPT','HPV1T','HPV2T'}, ...
      'HHHPT T', ...
      'T', ...
      {'HHH1T','HHH2T','HHHPT','HPV1T','HPV2T'}, ...
      varargin{:} );
