function phwvhkmzs(varargin);
% phwvhkmzs( [...] );
% MZ Set
h = timeplot({'MZ1St','MZ2St','MZ3St','MZ4St'}, ...
      'MZ Set', ...
      'Set', ...
      {'1','2','3','4'}, ...
      varargin{:} );
