function phwvhkmzct(varargin);
% phwvhkmzct( [...] );
% MZ CT
h = timeplot({'MZ1CT','MZ2CT','MZ3CT','MZ4CT'}, ...
      'MZ CT', ...
      'CT', ...
      {'1T','2T','3T','4T'}, ...
      varargin{:} );
