function phwvgais(varargin);
% phwvgais( [...] );
% General AI Stat
h = ne_dstat({
  'N0', 'AIStat', 0; ...
	'N1', 'AIStat', 1; ...
	'N0S', 'AIStat', 2; ...
	'N1S', 'AIStat', 3; ...
	'B4', 'AIStat', 4; ...
	'B5', 'AIStat', 5; ...
	'B6', 'AIStat', 6; ...
	'B7', 'AIStat', 7; ...
	'B8', 'AIStat', 8; ...
	'B9', 'AIStat', 9; ...
	'B10', 'AIStat', 10; ...
	'B11', 'AIStat', 11 }, 'AIStat', varargin{:} );
