function phwvhhhsspstatus(varargin);
% phwvhhhsspstatus( [...] );
% SSP Status
h = timeplot({'SSP_Status'}, ...
      'SSP Status', ...
      'Status', ...
      {'SSP\_Status'}, ...
      varargin{:} );
