function phwvlalasp(varargin);
% phwvlalasp( [...] );
% Lamp A Set Pt
h = timeplot({'HtASt','RFASt'}, ...
      'Lamp A Set Pt', ...
      'Set Pt', ...
      {'HtASt','RFASt'}, ...
      varargin{:} );
