function phwvhkdacst(varargin);
% phwvhkdacst( [...] );
% DACS T
h = timeplot({'DACS_T1C','DACS_T2C','vl_bdT','vl_cpuT'}, ...
      'DACS T', ...
      'T', ...
      {'DACS\_T1C','DACS\_T2C','vl\_bdT','vl\_cpuT'}, ...
      varargin{:} );
