function phwvsdpp(varargin);
% phwvsdpp( [...] );
% SDP P
h = timeplot({'SD_HP','SD_LP','UVB1_Counts'}, ...
      'SDP P', ...
      'P', ...
      {'SD\_HP','SD\_LP','UVB1\_Counts'}, ...
      varargin{:} );
