function phwvhkhkpc(varargin);
% phwvhkhkpc( [...] );
% HK Power Current
h = timeplot({'PM0I1','PM0I2'}, ...
      'HK Power Current', ...
      'Current', ...
      {'PM0I1','PM0I2'}, ...
      varargin{:} );
