function phwvlbt(varargin);
% phwvlbt( [...] );
% Lamp B Temp
h = timeplot({'B_LMT','B_RFT','ChpBT','FAB_T'}, ...
      'Lamp B Temp', ...
      'Temp', ...
      {'B\_LMT','B\_RFT','ChpBT','FAB\_T'}, ...
      varargin{:} );
