function phwvsdpt(varargin);
% phwvsdpt( [...] );
% SDP T
h = timeplot({'SDP_T'}, ...
      'SDP T', ...
      'T', ...
      {'SDP\_T'}, ...
      varargin{:} );
set(h,'LineStyle','none','Marker','.');
ax = get(h(1),'parent');
set(ax,'ylim',[-25 30]);
