function phwvcountsc(varargin);
% phwvcountsc( [...] );
% Counts C
h = timeplot({'PMTC_Counts','UVC1_Counts','UVC2_Counts'}, ...
      'Counts C', ...
      'C', ...
      {'PMTC\_Counts','UVC1\_Counts','UVC2\_Counts'}, ...
      varargin{:} );
