function phwvfpib(varargin);
% phwvfpib( [...] );
% Flow PIB
h = timeplot({'PIB1T','PIB2T','PIB3T','PIB4T','PIB5T','PIB6T','PIB7T'}, ...
      'Flow PIB', ...
      'PIB', ...
      {'1','2','3','4','5','6','7'}, ...
      varargin{:} );
