function phwvhhhfixfloat(varargin);
% phwvhhhfixfloat( [...] );
% icosfitd fixfloat
h = timeplot({'icosd_fixfloat'}, ...
      'icosfitd fixfloat', ...
      'fixfloat', ...
      {'icosd\_fixfloat'}, ...
      varargin{:} );
