function phwvhkcl(varargin);
% phwvhkcl( [...] );
% Current Lamps
h = timeplot({'LMA_I','LMB_I','LMC_I'}, ...
      'Current Lamps', ...
      'Lamps', ...
      {'LampA','LampB','LampC'}, ...
      varargin{:} );
