function phwvsdpp(varargin);
% phwvsdpp( [...] );
% SDP P
h = timeplot({'SD_HP','SD_LP','UVB1_Counts*0.08'}, ...
      'SDP P', ...
      'P', ...
      {'SD\_HP','SD\_LP','UVB1\_Counts'}, ...
      varargin{:} );
set(h,'LineStyle','none','Marker','.');
ax = get(h(1),'parent');
set(ax,'ylim',[0 800]);
