function phwvlbsp(varargin);
% phwvlbsp( [...] );
% Lamp B Set Pt
h = timeplot({'HtBSt','RFBSt','RFCSt'}, ...
      'Lamp B Set Pt', ...
      'Set Pt', ...
      {'HtBSt','RFBSt','RFCSt'}, ...
      varargin{:} );
