function phwvspvt(varargin);
% phwvspvt( [...] );
% SPV T
h = timeplot({'SPV1T','SPV2T','SPV_T1C','SPV_T2C'}, ...
      'SPV T', ...
      'T', ...
      {'SPV1T','SPV2T','SPV\_T1C','SPV\_T2C'}, ...
      varargin{:} );
