function phwvhkfpif(varargin);
% phwvhkfpif( [...] );
% Flow PIF
h = timeplot({'PIF1T','PIF2T','PIF3T','PIF4T','PIF5T','PIF6T','PIF7T'}, ...
      'Flow PIF', ...
      'PIF', ...
      {'1','2','3','4','5','6','7'}, ...
      varargin{:} );
