function phwvlalarf(varargin);
% phwvlalarf( [...] );
% Lamp A RF
h = timeplot({'ARFBW','ARFFW','RFASt'}, ...
      'Lamp A RF', ...
      'RF', ...
      {'BW','FW','RFASt'}, ...
      varargin{:} );
