function phwvsspt(varargin);
% phwvsspt( [...] );
% SSP T
h = timeplot({'SSP_T_FPGA','SSP_T_HtSink'}, ...
      'SSP T', ...
      'T', ...
      {'SSP\_T\_FPGA','SSP\_T\_HtSink'}, ...
      varargin{:} );
