function phwvhkps(varargin);
% phwvhkps( [...] );
% Power Switches
h = ne_dstat({
  'IOSW0', 'DS853', 4; ...
	'IOSW1', 'DS853', 5; ...
	'Flight', 'DS853', 6; ...
	'SpCPSw', 'DS853', 7 }, 'Switches', varargin{:} );
