function phwvlaairvdirvdt(varargin);
% phwvlaairvdirvdt( [...] );
% A IRV dIR Vdt
h = timeplot({'dIRVdt'}, ...
      'A IRV dIR Vdt', ...
      'dIR Vdt', ...
      {'dIRVdt'}, ...
      varargin{:} );
