function phwvlf(varargin);
% phwvlf( [...] );
% Lab Flow
h = timeplot({'L1Flw','L2Flw','L3Flw','L4Flw'}, ...
      'Lab Flow', ...
      'Flow', ...
      {'L1Flw','L2Flw','L3Flw','L4Flw'}, ...
      varargin{:} );
