function phwvsdpdp(varargin);
% phwvsdpdp( [...] );
% SDP DP
h = timeplot({'SDPDP'}, ...
      'SDP DP', ...
      'DP', ...
      {'SDPDP'}, ...
      varargin{:} );
set(h,'LineStyle','none','Marker','.');
ax = get(h,'parent');
set(ax,'ylim',[-.125 15]);
