function phwvhktmtd(varargin);
% phwvhktmtd( [...] );
% T Mbase T Drift
h = timeplot({'SysTDrift'}, ...
      'T Mbase T Drift', ...
      'T Drift', ...
      {'SysTDrift'}, ...
      varargin{:} );
