function phwvlaca(varargin);
% phwvlaca( [...] );
% Counts A
h = timeplot({'PMTA_Counts','UVA1_Counts','UVA2_Counts'}, ...
      'Counts A', ...
      'A', ...
      {'PMTA\_Counts','UVA1\_Counts','UVA2\_Counts'}, ...
      varargin{:} );
