function phwvhhhnu_f0(varargin);
% phwvhhhnu_f0( [...] );
% icosfitd nu F0
h = timeplot({'icos_nu_F0'}, ...
      'icosfitd nu F0', ...
      'nu F0', ...
      {'icos\_nu\_F0'}, ...
      varargin{:} );
