function phwvhkpv(varargin);
% phwvhkpv( [...] );
% HK Power Voltage
h = timeplot({'PM0V1','PM0V2'}, ...
      'HK Power Voltage', ...
      'Voltage', ...
      {'PM0V1','PM0V2'}, ...
      varargin{:} );
