function phwvlacb(varargin);
% phwvlacb( [...] );
% Counts B
h = timeplot({'PMTB_Counts','UVB1_Counts','UVB2_Counts'}, ...
      'Counts B', ...
      'B', ...
      {'PMTB\_Counts','UVB1\_Counts','UVB2\_Counts'}, ...
      varargin{:} );
